### ISSUE TITLE
No Commit_info and cannot get time of commit

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#24]
Hello:
     I'm using oscar.py to get the time of a specific commit.
    According to the instruction, I try to use Commit_info from oscar, but get

           ImportError: cannot import name 'Commit_info'

instead.
I didn't find other structures will give me the time of a given commit (specified by commit sha).
Could you let me know how can I do that?
A relevant question. I'm trying to use oscar.py to get all commits for a given project (specified by project slug). Right now I'm using Project(slug).commit_sha to get all of its commit sha and then get the time for each sha. Is there a more efficient way to that?

Thank you for your time.

**Comment by audrism** [comment]
What do you need? Project activity is precalculated in mongodb WoC.P_metadata.U

I personally don't use python interface (it is slow and not very up-to-date as Marat has very limited time for it and I and others don't want to destroy his great design by making any major modifications).

It may be worth while for you to start using command line rather than wait for python API to be fixed. 
Your query is:
```
cat listOfProj| getValues -f p2c | awk -F\; '{print $2";"$1}'|getValues c2dat 
```

**Comment by audrism** [comment]
Cleaned up docs
